/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/
export class AgendaDTO {

  compromissos: CompromissoDTO[];
  recursos: RecursoDTO[];

}


export class CompromissoDTO {

  id: string;
	titulo: string;
	cliente: string;
	dataIni: Date;
	horaIni: any;
	dataFim: Date;
	horaFim: any;
	diaTodo: boolean;
	situacao: string; /*CompromissoSituacao*/
	descricao: string;
	local: string;
	recursos: RecursoDTO[];
}

export class RecursoDTO {
  id: string;
	nome: string;
  email: string;
  compromissosCount: number;
}

export class ParametrosAgenda {

  ano: number;
  mes: number ;
  data: Date;
	recursoEmails: string[];

}

export class AgendaResumoDTO {
  compromissosCount: number;
}


export class SortField {
  field: string;
  order: number;

  constructor(field: string, order: number) {
    this.field = field;
    this.order = order;
  }
}

export class PaginationFilter {
  pageNumber: number;
  pageSize: number;
  sortFields: SortField[];

  constructor() {
    this.pageNumber = 0;
    this.pageSize = 10;
  }
}

export class AgendaListFilter extends PaginationFilter {


	// Map key=value for developer custom fields parameters. The final parameters map must be a JSON object.
	customParams = new Map<any, any>();
}

export class Agenda {
	id: string;
	nome: string;
}

export class AgendaAutoComplete {
	id: string;
	nome: string;
}

export class AgendaSumFields {
}
