/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { AgendaComponent } from './agenda.component';
import { RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';

import { AuthGuard } from './../../../security/auth.guard';

const routes: Routes = [
  // Must add in forRoot
  // { path: 'agenda', loadChildren: './modules/cadastros/cliente/agenda/agenda.module#AgendaModule' }
  {
    path: '',
    component: AgendaComponent,
    canActivate: [AuthGuard]
  }/*,
  {
    path: 'novo',
    component: AgendaComponent,
    canActivate: [AuthGuard]
  },
  {
    path: ':id',
    component: AgendaComponent,
    canActivate: [AuthGuard]
  }*/
];


@NgModule({

  imports: [
    RouterModule.forChild(routes)
  ],

  exports: [
    RouterModule
  ]

})

export class AgendaRoutingModule { }
