/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { ContaReceberComponent } from './crud-contareceber.component';
import { Injectable } from '@angular/core';

@Injectable()
export class CustomContaReceberService {

  component: ContaReceberComponent;

  setComponent(component: ContaReceberComponent) {
    this.component = component;
  }

  
  beforeConstructor(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterConstructor(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeOnInit(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterOnInit(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeOnNewRecord(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterOnNewRecord(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeSave(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterSave(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeCreate(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterCreate(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeUpdate(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterUpdate(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeGetById(id: string): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterGetById(id: string): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  actionFazerCopiasContaReceberHelp(): string {
  	// This method can be overridden.
  	return '';
  }
  
  
  beforeActionFazerCopiasContaReceber(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  afterActionFazerCopiasContaReceber(): boolean {
  	// This method can be overridden.
  	return true;
  }
  
  
  beforeContaPagaChange(event: any) {
  	// This method can be overridden.
  }
  

}

