/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { ContaReceberListComponent } from './list-contareceber.component';
import { Injectable } from '@angular/core';

import { ContaReceber } from './contareceber.model';

@Injectable()
export class CustomContaReceberListService {

  component: ContaReceberListComponent;

  setComponent(component: ContaReceberListComponent) {
    this.component = component;
  }

  
  applyRuleGridColumnsStyleClass_SituacaoConta(contaReceber: ContaReceber): String {
  	// This method can be overridden.
  	return null;
  }
  
  
  applyRuleAddColumnSituacaoContaGetValue(contaReceber: ContaReceber): String {
  	// This method can be overridden.
  	return null;
  }
  

}

