/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { CaixaDiario } from './../caixadiario/caixadiario.model';
import { TipoLancamentoFinanceiro } from './../enums/financeiro-fluxocaixa-enums.model';
import { FormaPagamento } from './../enums/financeiro-fluxocaixa-enums.model';
import { ContaBancaria } from './../contabancaria/contabancaria.model';
import { CartaoCredito } from './../cartaocredito/cartaocredito.model';
import { PlanoConta } from './../planoconta/planoconta.model';
import { Cliente } from './../cliente/cliente.model';
import { Fornecedor } from './../fornecedor/fornecedor.model';
import { TipoFonteMovimento } from './../enums/financeiro-fluxocaixa-enums.model';

export class SortField {
  field: string;
  order: number;

  constructor(field: string, order: number) {
    this.field = field;
    this.order = order;
  }
}

export class PaginationFilter {
  pageNumber: number;
  pageSize: number;
  sortFields: SortField[];

  constructor() {
    this.pageNumber = 0;
    this.pageSize = 10;
  }
}

export class CaixaLancamentoDescricaoAutoComplete {
	descricao: string;
}

export class CaixaLancamentoHistConcBancariaAutoComplete {
	histConcBancaria: string;
}

export class CaixaLancamentoListFilter extends PaginationFilter {
	
	descricao: CaixaLancamentoDescricaoAutoComplete[];
	
	dataLancamentoFrom: Date;
	dataLancamentoTo: Date;
	
	tipoLancamentoFinanceiro: TipoLancamentoFinanceiro;
	
	valorCreditoFrom: number;
	valorCreditoTo: number;
	
	valorDebitoFrom: number;
	valorDebitoTo: number;
	
	formaPagamento: FormaPagamento;
	
	idConcBancariaIsNotNull: boolean;
	
	histConcBancaria: CaixaLancamentoHistConcBancariaAutoComplete[];
	
	estornoIsNotNull: boolean;
	
	// Map key=value for developer custom fields parameters. The final parameters map must be a JSON object.
	customParams = new Map<any, any>();
}

export class CaixaLancamento {
	id: string;
	descricao: string;
	caixaDiario: CaixaDiario;
	dataLancamento: Date;
	tipoLancamentoFinanceiro: TipoLancamentoFinanceiro;
	valorCredito: number;
	valorDebito: number;
	formaPagamento: FormaPagamento;
	contaBancaria: ContaBancaria;
	cartaoCredito: CartaoCredito;
	outrosDescricao: string;
	planoContas: PlanoConta;
	cliente: Cliente;
	fornecedor: Fornecedor;
	maisOpcoes: boolean = false;
	documento: string;
	observacoes: string;
	idConcBancaria: string;
	histConcBancaria: string;
	numDocConcBancaria: string;
	estorno: boolean = false;
	estornoLancamento: CaixaLancamento;
	estornoHistorico: string;
	tipoFonteMovimento: TipoFonteMovimento;
	idFonteMovimento: string;
	version: number;
}

export class CaixaLancamentoAutoComplete {
	id: string;
	descricao: string;
	version: number;
}

export class CaixaLancamentoSumFields {
	sumValorCredito: number;
	sumValorDebito: number;
}
