/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import {MessageService} from 'primeng/api';

import { ElementRef, ViewChild } from '@angular/core';
import { Recurso } from './recurso.model';
import { RecursoService } from './recurso.service';
import { CadastrosClienteTranslationService } from './../i18n/cadastros-cliente-translation.service';
import * as moment from 'moment';
import { MessageHandlerService } from 'src/app/core/message-handler.service';


@Component({
  selector: 'app-crud-recurso',
  templateUrl: './crud-recurso.component.html',
  styleUrls: ['./crud-recurso.component.css']
})

export class RecursoComponent implements OnInit {
	showHideHelp = false; // for show/hide help.
	
	
	calendarLocale: any;
	
	recurso = new Recurso();
	
	@ViewChild('recurso_nome_elementRef', {static: true}) recursoDefaultElementRef: ElementRef;
	
	constructor(
	    private recursoService: RecursoService,
	    private cadastrosClienteTranslationService: CadastrosClienteTranslationService,
	    private route: ActivatedRoute,
	    private messageHandler: MessageHandlerService
	) { 
	}
	
	ngOnInit() {
		this.initLocaleSettings();
	    const id = this.route.snapshot.params['id'];
	    if (id) {
	      this.getRecursoById(id);
	    }
	    this.recursoDefaultElementSetFocus();
	}
	
	getShowHideHelpLabel(): string {
		return this.showHideHelp ? 'Ocultar ajuda' : 'Mostrar ajuda';
	}
	
	beginFormRecurso(form: FormControl) {
	    form.reset();
	    setTimeout(function() {
	      this.recurso = new Recurso();
		  this.recursoDefaultElementSetFocus();
	    }.bind(this), 1);
	}
	
	validateAllFormFields(form: FormGroup) {
	    Object.keys(form.controls).forEach(field => {
	      const control = form.get(field);
	
	      if (control instanceof FormControl) {
	        control.markAsDirty({ onlySelf: true });
	      } else if (control instanceof FormGroup) {
	        this.validateAllFormFields(control);
	      }
	    });
	}
	
	saveFormRecurso(form: FormGroup) {
		if (!form.valid) {
	      this.validateAllFormFields(form);
	      return;
	    }
	    if (this.isEditing) {
	      this.update();
	    } else {
	      this.create();
	    }
	}
	
	create() {
		
	    this.recursoService.create(this.recurso)
	    .then((recurso) => {
	      this.recurso = recurso;
	      this.messageHandler.showSuccess('Registro criado com sucesso!');
	      this.recursoDefaultElementSetFocus();
	    }).
	    catch(error => {
	      this.messageHandler.showError(error);
	    });
	}
	
	update() {
	    this.recursoService.update(this.recurso)
	    .then((recurso) => {
	      this.recurso = recurso;
	      this.messageHandler.showSuccess('Registro alterado!');
	      this.recursoDefaultElementSetFocus();
	    })
	    .catch(error => {
	      this.messageHandler.showError(error);
	    });
	}
	
	getRecursoById(id: string) {
	    this.recursoService.retrieve(id)
	    .then((recurso) => { 
	    	this.recurso = recurso;
	    })
	    .catch(error => {
	      this.messageHandler.showError(error);
	    });
	}
	
	get isEditing() {
	    return Boolean(this.recurso.id);
	}
	
	
	
	
	
	// TODO: temporário, só para testes.
	getTranslation(key: string): string {
		const value = this.cadastrosClienteTranslationService.getTranslation(key);
		return value;
		
		// const result = key.substring(key.lastIndexOf('_') + 1);
		// return result;
	}
	
	
	
	
	
	
	
	initLocaleSettings() {
		this.calendarLocale = this.cadastrosClienteTranslationService.getCalendarLocaleSettings();
	}
	
	
	
				
	recursoDefaultElementSetFocus() {
		try {
	    	this.recursoDefaultElementRef.nativeElement.focus();
	    } catch (error) {
	    	console.log('Error setting focus at recursoDefaultElementSetFocus:' + error);
	    }
	}
}
