/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


import { Injectable } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import * as moment from 'moment';

import { HttpClientWithToken } from '../../../../security/http-client-token';

import { Recurso } from './recurso.model';
import { RecursoAutoComplete } from './recurso.model';
import { RecursoListFilter } from './recurso.model';
import { RecursoNomeAutoComplete } from './recurso.model';
import { AnalyticsService } from './../../../../analitycs/analytics.service';
import { environment } from 'src/environments/environment';

@Injectable()
export class RecursoService {
	
	url = environment.apiUrl + '/cadastros/cliente/entities/recurso';
	
	constructor(
		private analitycs: AnalyticsService,
		private http: HttpClientWithToken) { 
		// Generated code.
	}
	
	// TODO: Provisório
	private getHeaders(): Headers {
		const headers = new Headers();
	    
	    headers.append('Content-Type', 'application/json');
	    return headers;
	}
	
	create(recurso: Recurso): Promise<Recurso> {
		const headers = this.getHeaders();    
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'create', 'create recurso');
	    return this.http.post(this.url, recurso, { headers })
	    .toPromise()
	    .then(response => {
	      const created = response as Recurso;
	      this.adjustEntityDates([created]);
	      return created;
	    });
	}
	
	update(recurso: Recurso): Promise<Recurso> {
	    const headers = this.getHeaders();
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'update', 'update recurso');
	    return this.http.put(`${this.url}/${recurso.id}`, recurso, { headers })
	    .toPromise()
	    .then(response => {
	      const updated = response as Recurso;
	      this.adjustEntityDates([updated]);
	      return updated;
	    });
	}
	
	delete(id: string): Promise<void> {
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'delete', 'delete recurso');
	    return this.http.delete(`${this.url}/${id}`)
	    .toPromise()
	    .then(() => null);
	}
	
	retrieve(id: string): Promise<Recurso> {
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'retrieve', 'retrieve recurso');
	    const headers = this.getHeaders();
	    return this.http.get<Recurso>(`${this.url}/${id}`, { headers })
	    .toPromise()
	    .then(response => {
	      const recurso = response as Recurso;
	      this.adjustEntityDates([recurso]);
	      return recurso;
	    });
	}
	
	
	private adjustEntityDates(entityList: Recurso[]) {
		entityList.forEach(recurso => {
		});
	}
	
	
	autoComplete(query: string): Promise<RecursoAutoComplete[]> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'autoComplete', JSON.stringify(params));
	    return this.http.get<RecursoAutoComplete[]>(`${this.url}/autoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as RecursoAutoComplete[];
	        return result;
	      });
	
	}
	
				
	
	recursoNomeAutoComplete(query: string): Promise<any> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'recursoNomeAutoComplete', JSON.stringify(params));
	    return this.http.get<any>(`${this.url}/recursoNomeAutoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as RecursoNomeAutoComplete[];
	        return result;
	      });
	
	}
	
	recursoList(recursoListFilter: RecursoListFilter): Promise<any> {
	    const headers = this.getHeaders();
	
	    const params = this.mountAndGetSearchParams(recursoListFilter);
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'recursoList', JSON.stringify(params));
	    return this.http.get<any>(this.url, { headers, params })
	      .toPromise()
	      .then(response => {
	        const data = response;
	        const items = data.content; /* array of Recurso */
	        const totalElements = data.totalElements;
	
	        this.adjustEntityDates(items);
	
	        const result = {
	          items,
	          totalElements
	        };
	
	        return result;
	      });
	}
	
	
	mountAndGetSearchParams(filter: RecursoListFilter): HttpParams {
	    let params = new HttpParams();
	    if (filter.pageNumber) {
	      params = params.set('page', filter.pageNumber.toString());
	    }
	
	    if (filter.pageSize) {
	      params = params.set('size', filter.pageSize.toString());
	    }
		
		// nome
		if (filter.nome) {
			const nome = filter.nome.map(item => item.nome).join(',');
			params = params.set('nome', nome);
		}
		
		// customParams
		if (filter.customParams && filter.customParams.size > 0) {
			const value = this.mapToJson(filter.customParams);
			params = params.set('customParams', value);
		}
	
	    // Sort
	    if (filter.sortFields) {
	      // search/nameStartsWith?name=K&sort=name,asc&sort=value,desc
	      
			filter.sortFields.forEach(sortField => {
				const sortValue = `${sortField.field},${sortField.order > 0 ? 'asc' : 'desc'}`;
				params = params.append('sort', sortValue);
			});
	    }
	
	    return params;
	}
	
 	mapToJson(someMap: Map<string, any>) {
      return JSON.stringify(this.mapToObj(someMap));
    }

    mapToObj(someMap: Map<string, any>) {
      const obj = Object.create(null);
      someMap.forEach((value, key) => {
        obj[key] = value;
      });
      return obj;
    }
	
	dateToStr(data: Date): string {
	    return moment(data).format('YYYY-MM-DD');
	}
	
	/*** TODO: avaliar se vai ser feito isso.
	replicateRecurso(id: string, groupId: string, quantity: number): Promise<boolean> {
	    const headers = this.getHeaders();
	
	    const payload = new ReplicateRecursoPayload(id, quantity, groupId);
	    return this.http.post(`${this.url}/replicateRecurso`, payload, { headers } )
	    .toPromise()
	    .then(response => {
	      return response === true;
	    });
	}
		
	getTotaisfilterRecurso(filter: RecursorListFilter): Promise<TotaisfilterRecurso> {
	    const headers = this.getHeaders();
		
	    const params = this.mountAndGetSearchParams(filter);
		this.analitycs.sendEvent('cadastros.cliente.recurso', 'getTotaisfilterRecurso', JSON.stringify(params));
	    return this.http.get<TotaisfilterRecurso>(`${this.url}/getTotaisfilterRecurso`, { headers, params })
	    .toPromise()
	    .then(response => {
	      const result = response as TotaisfilterRecurso;
	      return result;
	    });
	}
	*/
}

