/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { RecursoComponent } from './crud-recurso.component';
import { AuthGuard } from '../../../../security/auth.guard';
import { RecursoListComponent } from './list-recurso.component';
import { RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';

const routes: Routes = [
  // Must add in forRoot
  // { path: 'recurso', loadChildren: './modules/cadastros/cliente/recurso/recurso.module#RecursoModule' }
  {
    path: '',
    component: RecursoListComponent,
    canActivate: [AuthGuard]
  },
  {
    path: 'novo',
    component: RecursoComponent,
    canActivate: [AuthGuard]
  },
  {
    path: ':id',
    component: RecursoComponent,
    canActivate: [AuthGuard]
  }
];


@NgModule({

  imports: [
    RouterModule.forChild(routes)
  ],

  exports: [
    RouterModule
  ]

})

export class RecursoRoutingModule { }
