/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


import { Injectable } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import * as moment from 'moment';

import { HttpClientWithToken } from '../../../../security/http-client-token';

import { CartaoCredito } from './cartaocredito.model';
import { CartaoCreditoAutoComplete } from './cartaocredito.model';
import { Banco } from './../banco/banco.model';
import { BandeiraCartao } from './../bandeiracartao/bandeiracartao.model';
import { CartaoCreditoListFilter } from './cartaocredito.model';
import { AnalyticsService } from './../../../../analitycs/analytics.service';
import { environment } from 'src/environments/environment';
import { BancoAutoComplete } from './../banco/banco.model';
import { BandeiraCartaoAutoComplete } from './../bandeiracartao/bandeiracartao.model';

@Injectable()
export class CartaoCreditoService {
	
	url = environment.apiUrl + '/cadastros/banco/entities/cartaoCredito';
	
	constructor(
		private analitycs: AnalyticsService,
		private http: HttpClientWithToken) { 
		// Generated code.
	}
	
	// TODO: Provisório
	private getHeaders(): Headers {
		const headers = new Headers();
	    
	    headers.append('Content-Type', 'application/json');
	    return headers;
	}
	
	create(cartaoCredito: CartaoCredito): Promise<CartaoCredito> {
		const headers = this.getHeaders();    
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'create', 'create CartaoCredito');
	    return this.http.post(this.url, cartaoCredito, { headers })
	    .toPromise()
	    .then(response => {
	      const created = response as CartaoCredito;
	      this.adjustNullEntitySlots([created]);
	      this.adjustEntityDates([created]);
	      return created;
	    });
	}
	
	update(cartaoCredito: CartaoCredito): Promise<CartaoCredito> {
	    const headers = this.getHeaders();
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'update', 'update CartaoCredito');
	    return this.http.put(`${this.url}/${cartaoCredito.id}`, cartaoCredito, { headers })
	    .toPromise()
	    .then(response => {
	      const updated = response as CartaoCredito;
	      this.adjustNullEntitySlots([updated]);
	      this.adjustEntityDates([updated]);
	      return updated;
	    });
	}
	
	delete(id: string): Promise<void> {
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'delete', 'delete CartaoCredito');
	    return this.http.delete(`${this.url}/${id}`)
	    .toPromise()
	    .then(() => null);
	}
	
	retrieve(id: string): Promise<CartaoCredito> {
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'retrieve', 'retrieve CartaoCredito');
	    const headers = this.getHeaders();
	    return this.http.get<CartaoCredito>(`${this.url}/${id}`, { headers })
	    .toPromise()
	    .then(response => {
	      const cartaoCredito = response as CartaoCredito;
	      this.adjustNullEntitySlots([cartaoCredito]);
	      this.adjustEntityDates([cartaoCredito]);
	      return cartaoCredito;
	    });
	}
	
	
	private adjustEntityDates(entityList: CartaoCredito[]) {
		entityList.forEach(cartaoCredito => {
		      if (cartaoCredito.validade) {
		        cartaoCredito.validade = moment(cartaoCredito.validade, 'YYYY-MM-DD').toDate();
		      }
		      	
		});
	}
	
	private adjustNullEntitySlots(entityList: CartaoCredito[]) {
		/*entityList.forEach(cartaoCredito => {
		      if (!cartaoCredito.banco) {
		        cartaoCredito.banco = new Banco();
		      }
		      	
		      
		      if (!cartaoCredito.bandeiraCartao) {
		        cartaoCredito.bandeiraCartao = new BandeiraCartao();
		      }
		      	
		});*/
	}
	
	autoComplete(query: string): Promise<CartaoCreditoAutoComplete[]> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'autoComplete', JSON.stringify(params));
	    return this.http.get<CartaoCreditoAutoComplete[]>(`${this.url}/autoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as CartaoCreditoAutoComplete[];
	        return result;
	      });
	
	}
	
							
	// Begin relationships autoComplete 
	
	bancoBancoAutoComplete(query: string): Promise<BancoAutoComplete[]> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.banco.Banco', 'bancoBancoAutoComplete', JSON.stringify(params));
	    return this.http.get<BancoAutoComplete[]>(`${this.url}/bancoBancoAutoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as BancoAutoComplete[];
	        return result;
	      });
	
	}
	
	
	bandeiraCartaoBandeiraCartaoAutoComplete(query: string): Promise<BandeiraCartaoAutoComplete[]> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.banco.BandeiraCartao', 'bandeiraCartaoBandeiraCartaoAutoComplete', JSON.stringify(params));
	    return this.http.get<BandeiraCartaoAutoComplete[]>(`${this.url}/bandeiraCartaoBandeiraCartaoAutoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as BandeiraCartaoAutoComplete[];
	        return result;
	      });
	
	}
	
	// End relationships autoComplete
	
				
	
	cartaoCreditoList(cartaoCreditoListFilter: CartaoCreditoListFilter): Promise<any> {
	    const headers = this.getHeaders();
	
	    const params = this.mountAndGetSearchParams(cartaoCreditoListFilter);
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'cartaoCreditoList', JSON.stringify(params));
	    return this.http.get<any>(this.url, { headers, params })
	      .toPromise()
	      .then(response => {
	        const data = response;
	        const items = data.content; /* array of CartaoCredito */
	        const totalElements = data.totalElements;
	
	        this.adjustNullEntitySlots(items);
	        this.adjustEntityDates(items);
	
	        const result = {
	          items,
	          totalElements
	        };
	
	        return result;
	      });
	}
	
	
	mountAndGetSearchParams(filter: CartaoCreditoListFilter): HttpParams {
	    let params = new HttpParams();
	    if (filter.pageNumber) {
	      params = params.set('page', filter.pageNumber.toString());
	    }
	
	    if (filter.pageSize) {
	      params = params.set('size', filter.pageSize.toString());
	    }
		
		
		// customParams
		if (filter.customParams && filter.customParams.size > 0) {
			const value = this.mapToJson(filter.customParams);
			params = params.set('customParams', value);
		}
	
	    // Sort
	    if (filter.sortFields) {
	      // search/nameStartsWith?name=K&sort=name,asc&sort=value,desc
	      
			filter.sortFields.forEach(sortField => {
				const sortValue = `${sortField.field},${sortField.order > 0 ? 'asc' : 'desc'}`;
				params = params.append('sort', sortValue);
			});
	    }
	
	    return params;
	}
	
 	mapToJson(someMap: Map<string, any>) {
      return JSON.stringify(this.mapToObj(someMap));
    }

    mapToObj(someMap: Map<string, any>) {
      const obj = Object.create(null);
      someMap.forEach((value, key) => {
        obj[key] = value;
      });
      return obj;
    }
	
	dateToStr(data: Date): string {
	    return moment(data).format('YYYY-MM-DD');
	}
	
	/*** TODO: avaliar se vai ser feito isso.
	replicateCartaoCredito(id: string, groupId: string, quantity: number): Promise<boolean> {
	    const headers = this.getHeaders();
	
	    const payload = new ReplicateCartaoCreditoPayload(id, quantity, groupId);
	    return this.http.post(`${this.url}/replicateCartaoCredito`, payload, { headers } )
	    .toPromise()
	    .then(response => {
	      return response === true;
	    });
	}
		
	getTotaisfilterCartaoCredito(filter: CartaoCreditorListFilter): Promise<TotaisfilterCartaoCredito> {
	    const headers = this.getHeaders();
		
	    const params = this.mountAndGetSearchParams(filter);
		this.analitycs.sendEvent('cadastros.banco.CartaoCredito', 'getTotaisfilterCartaoCredito', JSON.stringify(params));
	    return this.http.get<TotaisfilterCartaoCredito>(`${this.url}/getTotaisfilterCartaoCredito`, { headers, params })
	    .toPromise()
	    .then(response => {
	      const result = response as TotaisfilterCartaoCredito;
	      return result;
	    });
	}
	*/
}

