/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


import { Injectable } from '@angular/core';
import { HttpParams } from '@angular/common/http';
import * as moment from 'moment';

import { HttpClientWithToken } from '../../../../security/http-client-token';

import { Cliente } from './cliente.model';
import { ClienteAutoComplete } from './cliente.model';
import { ClienteListFilter } from './cliente.model';
import { ClienteNomeAutoComplete } from './cliente.model';
import { AnalyticsService } from './../../../../analitycs/analytics.service';
import { environment } from 'src/environments/environment';

@Injectable()
export class ClienteService {
	
	url = environment.apiUrl + '/cadastros/cliente/entities/cliente';
	
	constructor(
		private analitycs: AnalyticsService,
		private http: HttpClientWithToken) { 
		// Generated code.
	}
	
	// TODO: Provisório
	private getHeaders(): Headers {
		const headers = new Headers();
	    
	    headers.append('Content-Type', 'application/json');
	    return headers;
	}
	
	create(cliente: Cliente): Promise<Cliente> {
		const headers = this.getHeaders();
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'create', 'create Cliente');
	    return this.http.post(this.url, cliente, { headers })
	    .toPromise()
	    .then(response => {
	      const created = response as Cliente;
	      this.adjustEntityDates([created]);
	      return created;
	    });
	}
	
	update(cliente: Cliente): Promise<Cliente> {
	    const headers = this.getHeaders();
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'update', 'update Cliente');
	    return this.http.put(`${this.url}/${cliente.id}`, cliente, { headers })
	    .toPromise()
	    .then(response => {
	      const updated = response as Cliente;
	      this.adjustEntityDates([updated]);
	      return updated;
	    });
	}
	
	delete(id: string): Promise<void> {
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'delete', 'delete Cliente');
	    return this.http.delete(`${this.url}/${id}`)
	    .toPromise()
	    .then(() => null);
	}
	
	retrieve(id: string): Promise<Cliente> {
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'retrieve', 'retrieve Cliente');
	    const headers = this.getHeaders();
	    return this.http.get<Cliente>(`${this.url}/${id}`, { headers })
	    .toPromise()
	    .then(response => {
	      const cliente = response as Cliente;
	      this.adjustEntityDates([cliente]);
	      return cliente;
	    });
	}
	
	
	private adjustEntityDates(entityList: Cliente[]) {
		entityList.forEach(cliente => {
		      if (cliente.dataFundacaoNascimento) {
		        cliente.dataFundacaoNascimento = moment(cliente.dataFundacaoNascimento, 'YYYY-MM-DD').toDate();
		      }
		      	
		});
	}
	
	
	
	autoComplete(query: string): Promise<ClienteAutoComplete[]> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'autoComplete', JSON.stringify(params));
	    return this.http.get<ClienteAutoComplete[]>(`${this.url}/autoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as ClienteAutoComplete[];
	        return result;
	      });
	
	}
	
				
	
	clienteNomeAutoComplete(query: string): Promise<any> {
	    const headers = this.getHeaders();
	
	    let params = new HttpParams();
	    params = params.set('query', query);
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'clienteNomeAutoComplete', JSON.stringify(params));
	    return this.http.get<any>(`${this.url}/clienteNomeAutoComplete`, { headers, params })
	      .toPromise()
	      .then(response => {
	        const result = response as ClienteNomeAutoComplete[];
	        return result;
	      });
	
	}
	
	clienteList(clienteListFilter: ClienteListFilter): Promise<any> {
	    const headers = this.getHeaders();
	
	    const params = this.mountAndGetSearchParams(clienteListFilter);
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'clienteList', JSON.stringify(params));
	    return this.http.get<any>(this.url, { headers, params })
	      .toPromise()
	      .then(response => {
	        const data = response;
	        const items = data.content; /* array of Cliente */
	        const totalElements = data.totalElements;
	
	        this.adjustEntityDates(items);
	
	        const result = {
	          items,
	          totalElements
	        };
	
	        return result;
	      });
	}
	
	
	mountAndGetSearchParams(filter: ClienteListFilter): HttpParams {
	    let params = new HttpParams();
	    if (filter.pageNumber) {
	      params = params.set('page', filter.pageNumber.toString());
	    }
	
	    if (filter.pageSize) {
	      params = params.set('size', filter.pageSize.toString());
	    }
		
		// nome
		if (filter.nome) {
			const nome = filter.nome.map(item => item.nome).join(',');
			params = params.set('nome', nome);
		}
		
		// customParams
		if (filter.customParams && filter.customParams.size > 0) {
			const value = this.mapToJson(filter.customParams);
			params = params.set('customParams', value);
		}
	
	    // Sort
	    if (filter.sortFields) {
	      // search/nameStartsWith?name=K&sort=name,asc&sort=value,desc
	      
			filter.sortFields.forEach(sortField => {
				const sortValue = `${sortField.field},${sortField.order > 0 ? 'asc' : 'desc'}`;
				params = params.append('sort', sortValue);
			});
	    }
	
	    return params;
	}
	
 	mapToJson(someMap: Map<string, any>) {
      return JSON.stringify(this.mapToObj(someMap));
    }

    mapToObj(someMap: Map<string, any>) {
      const obj = Object.create(null);
      someMap.forEach((value, key) => {
        obj[key] = value;
      });
      return obj;
    }
	
	dateToStr(data: Date): string {
	    return moment(data).format('YYYY-MM-DD');
	}
	
	/*** TODO: avaliar se vai ser feito isso.
	replicateCliente(id: string, groupId: string, quantity: number): Promise<boolean> {
	    const headers = this.getHeaders();
	
	    const payload = new ReplicateClientePayload(id, quantity, groupId);
	    return this.http.post(`${this.url}/replicateCliente`, payload, { headers } )
	    .toPromise()
	    .then(response => {
	      return response === true;
	    });
	}
		
	getTotaisfilterCliente(filter: ClienterListFilter): Promise<TotaisfilterCliente> {
	    const headers = this.getHeaders();
		
	    const params = this.mountAndGetSearchParams(filter);
		this.analitycs.sendEvent('cadastros.cliente.Cliente', 'getTotaisfilterCliente', JSON.stringify(params));
	    return this.http.get<TotaisfilterCliente>(`${this.url}/getTotaisfilterCliente`, { headers, params })
	    .toPromise()
	    .then(response => {
	      const result = response as TotaisfilterCliente;
	      return result;
	    });
	}
	*/
}

