/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgModule } from '@angular/core';
import { InputTextModule } from 'primeng/inputtext';
import { ButtonModule } from 'primeng/button';
import { InputTextareaModule } from 'primeng/inputtextarea';
import { TableModule } from 'primeng/table';
import { TooltipModule } from 'primeng/tooltip';
import { ToastModule } from 'primeng/toast';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { AutoCompleteModule } from 'primeng/autocomplete';
import { PanelModule } from 'primeng/panel';
import { InputSwitchModule } from 'primeng/inputswitch';
import { AccordionModule } from 'primeng/accordion';
import { SpinnerModule } from 'primeng/spinner';
import { DialogModule } from 'primeng/dialog';
import { DropdownModule } from 'primeng/dropdown';
import {CalendarModule} from 'primeng/calendar';
import { CurrencyMaskModule } from 'ng2-currency-mask';
import {CardModule} from 'primeng/card';

// Kerubin - BEGIN
import { FinanceiroContasPagarTranslationService } from './../i18n/./../i18n/financeiro-contaspagar-translation.service';
import { ContaPagarMultipleService } from './contapagarmultiple.service';
import { ContaPagarMultipleListComponent } from './list-contapagarmultiple.component';
import { ContaPagarMultipleComponent } from './crud-contapagarmultiple.component';
import { ContaPagarMultipleRoutingModule } from './contapagarmultiple-routing.module';
import { FornecedorModule } from '../fornecedor/fornecedor.module';
import { ContaBancariaModule } from '../contabancaria/contabancaria.module';
import { CartaoCreditoModule } from '../cartaocredito/cartaocredito.module';
import { PlanoContaModule } from '../planoconta/planoconta.module';
import { ContaPagarModule } from '../contapagar/contapagar.module';
// Kerubin - END

@NgModule({

  imports: [
    // PrimeNG
    CommonModule,
	FormsModule,
	InputTextModule,
	ButtonModule,
	InputTextareaModule,
	TableModule,
	TooltipModule,
	ToastModule,
	ConfirmDialogModule,
	AutoCompleteModule,
	PanelModule,
	InputSwitchModule,
	AccordionModule,
	SpinnerModule,
	DialogModule,
	DropdownModule,
	CalendarModule,
	CurrencyMaskModule,
	CardModule,

    // Kerubin
    ContaPagarMultipleRoutingModule,
	FornecedorModule,
	ContaBancariaModule,
	CartaoCreditoModule,
	PlanoContaModule
	// ,ContaPagarModule

  ],

  declarations: [
    ContaPagarMultipleComponent,
    ContaPagarMultipleListComponent
  ],

  exports: [
    ContaPagarMultipleComponent,
    ContaPagarMultipleListComponent
  ],

  providers: [
    ContaPagarMultipleService,
    FinanceiroContasPagarTranslationService
  ]

})

export class ContaPagarMultipleModule { }
