/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { ContaPagarMultipleComponent } from './crud-contapagarmultiple.component';
import { AuthGuard } from '../../../../security/auth.guard';
import { ContaPagarMultipleListComponent } from './list-contapagarmultiple.component';
import { RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';

const routes: Routes = [
  // Must add in forRoot
  // { path: 'contapagarmultiple', loadChildren: './modules/financeiro/contas_pagar/contapagarmultiple/contapagarmultiple.module#ContaPagarMultipleModule' }
  {
    path: '',
    component: ContaPagarMultipleListComponent,
    canActivate: [AuthGuard]
  },
  {
    path: 'novo',
    component: ContaPagarMultipleComponent,
    canActivate: [AuthGuard]
  },
  {
    path: ':id',
    component: ContaPagarMultipleComponent,
    canActivate: [AuthGuard]
  }
];


@NgModule({

  imports: [
    RouterModule.forChild(routes)
  ],

  exports: [
    RouterModule
  ]

})

export class ContaPagarMultipleRoutingModule { }
