/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { FotoComponent } from './crud-foto.component';
import { AuthGuard } from '../../../../security/auth.guard';
import { FotoListComponent } from './list-foto.component';
import { RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';

const routes: Routes = [
  // Must add in forRoot
  // { path: 'foto', loadChildren: './modules/cadastros/fornecedor/foto/foto.module#FotoModule' }
  {
    path: '',
    component: FotoListComponent,
    canActivate: [AuthGuard]
  },
  {
    path: 'novo',
    component: FotoComponent,
    canActivate: [AuthGuard]
  },
  {
    path: ':id',
    component: FotoComponent,
    canActivate: [AuthGuard]
  }
];


@NgModule({

  imports: [
    RouterModule.forChild(routes)
  ],

  exports: [
    RouterModule
  ]

})

export class FotoRoutingModule { }
