/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


import { Component, OnInit } from '@angular/core';
import {ConfirmationService, LazyLoadEvent, SelectItem} from 'primeng/api';
import { Dropdown } from 'primeng/dropdown';
import * as moment from 'moment';
import { MessageHandlerService } from 'src/app/core/message-handler.service';

import { FotoService } from './foto.service';
import { CadastrosFornecedorTranslationService } from './../i18n/cadastros-fornecedor-translation.service';
import { Foto } from './foto.model';
import { FotoListFilter } from './foto.model';
import { SortField } from './foto.model';

import { ProdutoAutoComplete } from './../produto/produto.model';

@Component({
  selector: 'app-list-foto',
  templateUrl: './list-foto.component.html',
  styleUrls: ['./list-foto.component.css']
})

export class FotoListComponent implements OnInit {
	tableLoading = false;
	
	fotoListItems: Foto[];
	fotoListTotalElements = 0;
	fotoListFilter = new FotoListFilter();
	
	
	
	
	constructor(
	    private fotoService: FotoService,
	    private cadastrosFornecedorTranslationService: CadastrosFornecedorTranslationService,
	    private confirmation: ConfirmationService,
	    private messageHandler: MessageHandlerService
	) { 
	}
	
	ngOnInit() {
	}
	
	fotoList(pageNumber = 0) {
		this.tableLoading = true;
	    this.fotoListFilter.pageNumber = pageNumber;
	    this.fotoService
	    .fotoList(this.fotoListFilter)
	    .then(result => {
	    	try {
		      	this.fotoListItems = result.items;
		      	this.fotoListTotalElements = result.totalElements;
		      
			} finally {
				this.tableLoading = false;
			}
	    })
	    .catch(e => {
	    	this.tableLoading = false;
	    });
		
	}
	
	
	fotoFilterSearch() {
	    this.fotoList(0);
	}
	
	deleteFoto(foto: Foto) {
	    this.confirmation.confirm({
	      message: 'Confirma a exclusão do registro?',
	      accept: () => {
	        this.fotoService.delete(foto.id)
	        .then(() => {
	          this.messageHandler.showSuccess('Registro excluído!');
	          this.fotoList(0);
	        })
	        .catch((e) => {
	          this.messageHandler.showError(e);
	        });
	      }
	    });
	}
	
	fotoListOnLazyLoad(event: LazyLoadEvent) {
	    if (event.multiSortMeta) {
	      this.fotoListFilter.sortFields = new Array(event.multiSortMeta.length);
	      event.multiSortMeta.forEach(sortField => {
	      	this.fotoListFilter.sortFields.push(new SortField(sortField.field, sortField.order));
	      });
	    } else {
	    	this.fotoListFilter.sortFields = new Array(1);
	    	this.fotoListFilter.sortFields.push(new SortField('id', 1)); // asc
	    }
	    const pageNumber = event.first / event.rows;
	    this.fotoListFilter.pageSize = event.rows;
	    this.fotoList(pageNumber);
	}
	
	
	
	fotoProdutoAutoCompleteFieldConverter(produto: ProdutoAutoComplete) {
		if (produto) {
			return (produto.nome || '<nulo>');
		} else {
			return null;
		}
	}
	
	
	
	
	// TODO: temporário, só para testes.
	getTranslation(key: string): string {
		const value = this.cadastrosFornecedorTranslationService.getTranslation(key);
		return value;
		
		// const result = key.substring(key.lastIndexOf('_') + 1);
		// return result;
	}
	
	
}
