/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { TipoContaBancaria } from './../enums/cadastros-banco-enums.model';
import { AgenciaBancaria } from './../agenciabancaria/agenciabancaria.model';
import { BandeiraCartao } from './../bandeiracartao/bandeiracartao.model';

export class SortField {
  field: string;
  order: number;

  constructor(field: string, order: number) {
    this.field = field;
    this.order = order;
  }
}

export class PaginationFilter {
  pageNumber: number;
  pageSize: number;
  sortFields: SortField[];

  constructor() {
    this.pageNumber = 0;
    this.pageSize = 10;
  }
}

export class ContaBancariaNumeroContaAutoComplete {
	numeroConta: string;
}

export class ContaBancariaListFilter extends PaginationFilter {
	
	numeroConta: ContaBancariaNumeroContaAutoComplete[];
	
	// Map key=value for developer custom fields parameters. The final parameters map must be a JSON object.
	customParams = new Map<any, any>();
}

export class ContaBancaria {
	id: string;
	nomeTitular: string;
	cpfCnpjTitular: string;
	tipoContaBancaria: TipoContaBancaria;
	agencia: AgenciaBancaria;
	numeroConta: string;
	digito: string;
	saldo: number;
	maisOpcoes: boolean = false;
	ativo: boolean = true;
	dataValidade: Date;
	numeroCartao: string;
	codigoSeguranca: string;
	bandeiraCartao: BandeiraCartao;
}

export class ContaBancariaAutoComplete {
	id: string;
	nomeTitular: string;
	cpfCnpjTitular: string;
	numeroConta: string;
	digito: string;
}

export class ContaBancariaSumFields {
}
