/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { SelectItem } from 'primeng/api';

export interface TipoPessoa extends SelectItem {
	
  label?: string;
  value: any;
  
}

export interface UF extends SelectItem {
	
  label?: string;
  value: any;
  
}

