/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/


import { Component, OnInit } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import {MessageService} from 'primeng/api';

import { ElementRef, ViewChild } from '@angular/core';
import { Caixa } from './caixa.model';
import { CaixaService } from './caixa.service';
import { FinanceiroFluxoCaixaTranslationService } from './../i18n/financeiro-fluxocaixa-translation.service';
import * as moment from 'moment';
import { MessageHandlerService } from 'src/app/core/message-handler.service';


@Component({
  selector: 'app-crud-caixa',
  templateUrl: './crud-caixa.component.html',
  styleUrls: ['./crud-caixa.component.css']
})

export class CaixaComponent implements OnInit {
	showHideHelp = false; // for show/hide help.
	
	
	calendarLocale: any;
	
	caixa = new Caixa();
	
	@ViewChild('caixa_nome_elementRef', {static: true}) caixaDefaultElementRef: ElementRef;
	
	constructor(
	    private caixaService: CaixaService,
	    private financeiroFluxoCaixaTranslationService: FinanceiroFluxoCaixaTranslationService,
	    private route: ActivatedRoute,
	    private messageHandler: MessageHandlerService
	) { 
	}
	
	ngOnInit() {
		this.initLocaleSettings();
		this.rulesOnCreate();
		
	    const id = this.route.snapshot.params['id'];
	    if (id) {
	      this.getCaixaById(id);
	    }
	    this.caixaDefaultElementSetFocus();
	}
	
	getShowHideHelpLabel(): string {
		return this.showHideHelp ? 'Ocultar ajuda' : 'Mostrar ajuda';
	}
	
	beginFormCaixa(form: FormControl) {
	    form.reset();
	    setTimeout(function() {
	      this.caixa = new Caixa();
		  this.caixaDefaultElementSetFocus();
	    }.bind(this), 1);
	}
	
	validateAllFormFields(form: FormGroup) {
	    Object.keys(form.controls).forEach(field => {
	      const control = form.get(field);
	
	      if (control instanceof FormControl) {
	        control.markAsDirty({ onlySelf: true });
	      } else if (control instanceof FormGroup) {
	        this.validateAllFormFields(control);
	      }
	    });
	}
	
	saveFormCaixa(form: FormGroup) {
		if (!form.valid) {
	      this.validateAllFormFields(form);
	      return;
	    }
	    if (this.isEditing) {
	      this.update();
	    } else {
	      this.create();
	    }
	}
	
	create() {
		this.rulesOnCreate();
		
	    this.caixaService.create(this.caixa)
	    .then((caixa) => {
	      this.caixa = caixa;
	      this.messageHandler.showSuccess('Registro criado com sucesso!');
	      this.caixaDefaultElementSetFocus();
	    }).
	    catch(error => {
	      this.messageHandler.showError(error);
	    });
	}
	
	update() {
	    this.caixaService.update(this.caixa)
	    .then((caixa) => {
	      this.caixa = caixa;
	      this.messageHandler.showSuccess('Registro alterado!');
	      this.caixaDefaultElementSetFocus();
	    })
	    .catch(error => {
	      this.messageHandler.showError(error);
	    });
	}
	
	getCaixaById(id: string) {
	    this.caixaService.retrieve(id)
	    .then((caixa) => { 
	    	this.caixa = caixa;
	    })
	    .catch(error => {
	      this.messageHandler.showError(error);
	    });
	}
	
	get isEditing() {
	    return Boolean(this.caixa.id);
	}
	
	
	
	
	
	// TODO: temporário, só para testes.
	getTranslation(key: string): string {
		const value = this.financeiroFluxoCaixaTranslationService.getTranslation(key);
		return value;
		
		// const result = key.substring(key.lastIndexOf('_') + 1);
		// return result;
	}
	
	rulesOnCreate() {
		this.caixa.saldo = 0.0;
	}
	
	
	
	
										
	// Begin RuleDisableComponent 
	
	nomeRuleDisableComponent() {
		const expression = this.caixa.id && (String(this.caixa.id) === 'bd1e9cb7-e7f6-40da-af5c-1f461dac1d11');
		return expression;
	}
	
	ativoRuleDisableComponent() {
		const expression = this.caixa.id && (String(this.caixa.id) === 'bd1e9cb7-e7f6-40da-af5c-1f461dac1d11');
		return expression;
	}
	
	observacoesRuleDisableComponent() {
		const expression = this.caixa.id && (String(this.caixa.id) === 'bd1e9cb7-e7f6-40da-af5c-1f461dac1d11');
		return expression;
	}
	// End Begin RuleDisableComponent
	
	
	
	caixaRuleDisableCUD() {
		const expression = this.caixa.id && (String(this.caixa.id) === 'bd1e9cb7-e7f6-40da-af5c-1f461dac1d11');
		return expression;
	}
	
	initLocaleSettings() {
		this.calendarLocale = this.financeiroFluxoCaixaTranslationService.getCalendarLocaleSettings();
	}
	
	
	
				
	caixaDefaultElementSetFocus() {
		try {
	    	this.caixaDefaultElementRef.nativeElement.focus();
	    } catch (error) {
	    	console.log('Error setting focus at caixaDefaultElementSetFocus:' + error);
	    }
	}
}
