/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { Cliente } from './../cliente/cliente.model';
import { Recurso } from './../recurso/recurso.model';

export class SortField {
  field: string;
  order: number;

  constructor(field: string, order: number) {
    this.field = field;
    this.order = order;
  }
}

export class PaginationFilter {
  pageNumber: number;
  pageSize: number;
  sortFields: SortField[];

  constructor() {
    this.pageNumber = 0;
    this.pageSize = 10;
  }
}

export class CompromissoTituloAutoComplete {
	titulo: string;
}

export class CompromissoListFilter extends PaginationFilter {
	
	titulo: CompromissoTituloAutoComplete[];
	
	// Map key=value for developer custom fields parameters. The final parameters map must be a JSON object.
	customParams = new Map<any, any>();
}

export class Compromisso {
	id: string;
	titulo: string;
	cliente: Cliente;
	dataIni: Date;
	horaIni: Date;
	dataFim: Date;
	horaFim: Date;
	diaTodo: boolean = false;
	descricao: string;
	local: string;
	recursos: Recurso[];
}

export class CompromissoAutoComplete {
	id: string;
	titulo: string;
}

export class CompromissoSumFields {
}
