/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { ProdutoComponent } from './crud-produto.component';
import { AuthGuard } from '../../../../security/auth.guard';
import { ProdutoListComponent } from './list-produto.component';
import { RouterModule, Routes } from '@angular/router';
import { NgModule } from '@angular/core';

const routes: Routes = [
  // Must add in forRoot/
  // { path: 'produto', loadChildren: './modules/cadastros/fornecedor/produto/produto.module#ProdutoModule' }
  {
    path: '',
    component: ProdutoListComponent,
    canActivate: [AuthGuard]
  },
  {
    path: 'novo',
    component: ProdutoComponent,
    canActivate: [AuthGuard]
  },
  {
    path: ':id',
    component: ProdutoComponent,
    canActivate: [AuthGuard]
  }
];


@NgModule({

  imports: [
    RouterModule.forChild(routes)
  ],

  exports: [
    RouterModule
  ]

})

export class ProdutoRoutingModule { }
