/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { PlanoConta } from './../planoconta/planoconta.model';
import { FormaPagamento } from './../enums/financeiro-contaspagar-enums.model';
import { ContaBancaria } from './../contabancaria/contabancaria.model';
import { CartaoCredito } from './../cartaocredito/cartaocredito.model';
import { Fornecedor } from './../fornecedor/fornecedor.model';

export class SortField {
  field: string;
  order: number;

  constructor(field: string, order: number) {
    this.field = field;
    this.order = order;
  }
}

export class PaginationFilter {
  pageNumber: number;
  pageSize: number;
  sortFields: SortField[];

  constructor() {
    this.pageNumber = 0;
    this.pageSize = 10;
  }
}

export class ContaPagarDescricaoAutoComplete {
	descricao: string;
}

export class ContaPagarHistConcBancariaAutoComplete {
	histConcBancaria: string;
}

export class ContaPagarAgrupadorAutoComplete {
	agrupador: string;
}

export class ContaPagarListFilter extends PaginationFilter {

	descricao: ContaPagarDescricaoAutoComplete[];

	dataVencimentoFrom: Date;
	dataVencimentoTo: Date;

	valorFrom: number;
	valorTo: number;

	formaPagamento: FormaPagamento;

	dataPagamentoIsNotNull: boolean;
	dataPagamentoIsNull: boolean;

	idConcBancariaIsNotNull: boolean;

	histConcBancaria: ContaPagarHistConcBancariaAutoComplete[];

	agrupador: ContaPagarAgrupadorAutoComplete[];

	// Map key=value for developer custom fields parameters. The final parameters map must be a JSON object.
	customParams = new Map<any, any>();
}

export class ContaPagar {
	id: string;
	descricao: string;
	planoContas: PlanoConta;
	dataVencimento: Date;
	valor: number;
	formaPagamento: FormaPagamento;
	contaBancaria: ContaBancaria;
	cartaoCredito: CartaoCredito;
	outrosDescricao: string;
	fornecedor: Fornecedor;
	contaPaga: boolean = false;
	dataPagamento: Date;
	valorDesconto: number;
	valorMulta: number;
	valorJuros: number;
	valorAcrescimos: number;
	valorPago: number;
	maisOpcoes: boolean = false;
	idConcBancaria: string;
	histConcBancaria: string;
	numDocConcBancaria: string;
	numDocumento: string;
	observacoes: string;
	agrupador: string;
}

export class ContaPagarAutoComplete {
	id: string;
	descricao: string;
}

export class ContaPagarSumFields {
	sumValor: number;
	sumValorDesconto: number;
	sumValorMulta: number;
	sumValorJuros: number;
	sumValorAcrescimos: number;
	sumValorPago: number;
}


export class ContaPagarMultiple {
  id: string;
	dataPagamento: Date;
	valorPago: number;
  descricao: string;
  planoContas: PlanoConta;
	formaPagamento: FormaPagamento;
	contaBancaria: ContaBancaria;
	cartaoCredito: CartaoCredito;
  fornecedor: Fornecedor;
  contaPagarId: string;
}
