/**********************************************************************************************
Code generated by MKL Plug-in
Copyright: Kerubin - kerubin.platform@gmail.com

WARNING: DO NOT CHANGE THIS CODE BECAUSE THE CHANGES WILL BE LOST IN THE NEXT CODE GENERATION.
***********************************************************************************************/

import { ContaPagarListComponent } from './list-contapagar.component';
import { Injectable } from '@angular/core';

import { ContaPagar } from './contapagar.model';

@Injectable()
export class CustomContaPagarListService {

  component: ContaPagarListComponent;

  setComponent(component: ContaPagarListComponent) {
    this.component = component;
  }

  
  applyRuleGridColumnsStyleClass_SituacaoConta(contaPagar: ContaPagar): String {
  	// This method can be overridden.
  	return null;
  }
  
  
  applyRuleAddColumnSituacaoContaGetValue(contaPagar: ContaPagar): String {
  	// This method can be overridden.
  	return null;
  }
  

}

